### ISSUE TITLE
Permissive license

### ISSUE THREAD

**Issue by ayberkt** [traiansf/language-k#1]
Hi @traiansf!

I am trying to use the grammar in this repo to get K into [GitHub linguist](https://github.com/github/linguist). They are asking for this repo to have a permissive license. Is it possible that you add one of the following licenses?

- apache-2.0
- bsd-2-clause
- bsd-3-clause
- permissive
- mit
- isc
- mpl-2.0
- unlicense
- wtfpl
- zlib

The discussion of this issue is ongoing in github/linguist#3689.

**Comment by traiansf** [comment]
I have nothing against any of the mentioned licenses. Could you please make a pull request with one of them? I'll make sure to approve it.

**Comment by ayberkt** [comment]
Hi @traiansf, would you mind merging this? Thanks!

**Comment by traiansf** [comment]
@ayberkt Thanks!
